In [11]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a=array(100)


In [18]:
import numpy as a
a=a.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b=2
b

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [33]:
b=np.array([1,5,999])
c=b.sum()
print(c)


1005


In [37]:
import numpy as a
a=a.array([[1,2,3],[4,5,6],[7,8,9]])
print(len(a))
print(a.dtype)
print(a)


3
int32
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
a=np.array(['a','e','i','o','u'])
print(a)

print(a.ndim)
print(a.shape)
print(a.dtype)
print(a[0:2])

['a' 'e' 'i' 'o' 'u']
1
(5,)
<U1
['a' 'e']


In [49]:

b=np.eye(3,2)

b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [3]:
import numpy as np
f=np.linspace(90,110,100)
f

array([ 90.        ,  90.2020202 ,  90.4040404 ,  90.60606061,
        90.80808081,  91.01010101,  91.21212121,  91.41414141,
        91.61616162,  91.81818182,  92.02020202,  92.22222222,
        92.42424242,  92.62626263,  92.82828283,  93.03030303,
        93.23232323,  93.43434343,  93.63636364,  93.83838384,
        94.04040404,  94.24242424,  94.44444444,  94.64646465,
        94.84848485,  95.05050505,  95.25252525,  95.45454545,
        95.65656566,  95.85858586,  96.06060606,  96.26262626,
        96.46464646,  96.66666667,  96.86868687,  97.07070707,
        97.27272727,  97.47474747,  97.67676768,  97.87878788,
        98.08080808,  98.28282828,  98.48484848,  98.68686869,
        98.88888889,  99.09090909,  99.29292929,  99.49494949,
        99.6969697 ,  99.8989899 , 100.1010101 , 100.3030303 ,
       100.50505051, 100.70707071, 100.90909091, 101.11111111,
       101.31313131, 101.51515152, 101.71717172, 101.91919192,
       102.12121212, 102.32323232, 102.52525253, 102.72

In [4]:
a=np.diag([1,2,3,4])
x=np.diag(a)
x

array([1, 2, 3, 4])

In [5]:
b=np.random.rand(5)
b

array([0.39096726, 0.32519727, 0.4756857 , 0.67030115, 0.28978007])

In [7]:
c=np.random.randn(5)
c

array([-0.97398859,  0.61792054,  0.89649305, -0.84457887, -1.68772046])

In [8]:
d=np.array([1,2,3,4,5,],dtype='float64')
d

array([1., 2., 3., 4., 5.])

In [19]:
t=[1,2,3,4,5,6,7,8]
list1=t[0:5]
list1[2]=9
t

[1, 2, 3, 4, 5, 6, 7, 8]

In [21]:
a=np.array([1,2,3,4,5,6,7,8])
b=a[0:5].copy()
b[2]=9
b
np.shares_memory(a,b)

False

In [26]:
x=np.random.randint(50,100,100)
x

array([58, 90, 98, 79, 74, 52, 60, 78, 97, 70, 53, 90, 81, 71, 68, 53, 68,
       70, 55, 81, 55, 84, 82, 99, 99, 82, 59, 83, 55, 90, 87, 89, 51, 78,
       73, 72, 59, 99, 97, 75, 69, 83, 61, 73, 73, 51, 71, 98, 83, 54, 52,
       74, 77, 72, 53, 76, 67, 62, 82, 81, 74, 99, 74, 79, 93, 73, 58, 57,
       50, 68, 86, 98, 94, 71, 64, 75, 85, 60, 97, 57, 76, 58, 95, 94, 92,
       88, 95, 76, 70, 71, 97, 64, 58, 55, 57, 85, 94, 54, 78, 83])

In [30]:
mask=(x%2==0)
y=x[mask]
y

array([58, 90, 98, 74, 52, 60, 78, 70, 90, 68, 68, 70, 84, 82, 82, 90, 78,
       72, 98, 54, 52, 74, 72, 76, 62, 82, 74, 74, 58, 50, 68, 86, 98, 94,
       64, 60, 76, 58, 94, 92, 88, 76, 70, 64, 58, 94, 54, 78])

In [32]:
z=(y%3==0)
m=y[z]
m

array([90, 60, 78, 90, 84, 90, 78, 72, 54, 72, 60, 54, 78])

In [33]:
x[[1,5,9]]=10000
x

array([   58, 10000,    98,    79,    74, 10000,    60,    78,    97,
       10000,    53,    90,    81,    71,    68,    53,    68,    70,
          55,    81,    55,    84,    82,    99,    99,    82,    59,
          83,    55,    90,    87,    89,    51,    78,    73,    72,
          59,    99,    97,    75,    69,    83,    61,    73,    73,
          51,    71,    98,    83,    54,    52,    74,    77,    72,
          53,    76,    67,    62,    82,    81,    74,    99,    74,
          79,    93,    73,    58,    57,    50,    68,    86,    98,
          94,    71,    64,    75,    85,    60,    97,    57,    76,
          58,    95,    94,    92,    88,    95,    76,    70,    71,
          97,    64,    58,    55,    57,    85,    94,    54,    78,
          83])

In [36]:
a=np.array([[1,2],[3,4]])
a.sum(axis=0)


array([4, 6])

In [37]:
a=np.array([[1,2],[3,4]])
a.sum(axis=1)


array([3, 7])