In [7]:
#mathematics

import numpy as np

a=np.array([1,2,3,4])
a+=2
a/2

array([1.5, 2. , 2.5, 3. ])

In [4]:
b=np.array([1,0,1,0])
#a**2


NameError: name 'np' is not defined

In [14]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [30]:
np.lcm(2,3)
x=np.array([1,2,3,5])
np.gcd.reduce(x)

1

In [12]:
#linear algebra

a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
b=np.full((3,2),10)
b

array([[10, 10],
       [10, 10],
       [10, 10]])

In [14]:
np.matmul(a,b)

array([[30., 30.],
       [30., 30.]])

In [16]:
c=np.identity(3)
np.linalg.det(c)

1.0

In [39]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
#statstics

s=np.array([[1,2,3],[4,5,6]])
np.min(s)
np.max(s,axis=1)
#axis=0=>columns,axis=1=>rows
#np.mean(s)
#np.median(s)
#np.var(s)
#np.sum(s)

array([3, 6])

In [61]:
#reshaping

x=np.array([[1,2,3,4],[5,6,7,8]])
y=x.reshape((2,2,2))
y

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [63]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
h1=np.array([1,2,3,4])
h2=np.array([5,6,7,8])
np.hstack([h1,h2,h1,h2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [72]:

#load from a file(.txt)
filedata=np.genfromtxt('C:\\Users\\srinivas\\Desktop\\x.txt')
filedata=filedata.astype('int32')
print(filedata)

ValueError: Some errors were detected !
    Line #2 (got 8 columns instead of 9)
    Line #3 (got 10 columns instead of 9)
    Line #4 (got 14 columns instead of 9)
    Line #5 (got 14 columns instead of 9)
    Line #6 (got 10 columns instead of 9)
    Line #7 (got 8 columns instead of 9)

In [85]:
#boolean masking and indexing
x=np.array([1,2,3,4,5,6])
np.all(x>0,axis=0)
np.any(~(x>=1),axis=0)
#x[[1,2,3]]

False

In [ ]:
1  2  3  4  5
6  7  8  9  10
11 12 13 14 15
16 17 18 19 20
21 22 23 24 25
26 27 28 29 30

In [ ]:
1(2,8,14,20),2(11,12,16,17),3(4,5,24,25,29,30)

In [ ]:
####WHO COMPLETES THE ABOVE TASK GETS gmail sending and notification alerting using python

