In [1]:
print('hello world')

hello world


In [ ]:

NumPy

In [17]:
import numpy as np
a=np.array([1,2,3])
print(a)
print()
print()
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[1 2 3]


[[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
print(a.ndim)
pritn(b.ndim)

2

In [19]:
print(a.shape)

print(b.shape)

(3,)
(2, 3)


In [24]:
print(a.dtype)
print(a.itemsize)

int32
4


In [27]:
a=np.array([1,2,3],dtype='int16')
print(a.dtype)
print(a.itemsize)

int16
2


In [29]:
a.size

3

In [33]:
#a.size*a.itemsize

a.nbytes

6

In [35]:
#accessing/changing

a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [36]:
a.shape

(2, 7)

In [40]:
#[r,c]

print(a[0,-2])

6


In [45]:
print(a[0,:])
print(a[:,3])


[1 2 3 4 5 6 7]
[ 4 11]


In [52]:
a[0,0:6:2]

array([1, 3, 5])

In [51]:
a[0,0:-1:2]

array([1, 3, 5])

In [54]:
a[1,-2]=20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [55]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [60]:
#b[box,row,column]

b[0,1,-2]

3

In [58]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [62]:
b[:,1,:]=[[420,420],[786,786]]
b

array([[[  1,   2],
        [420, 420]],

       [[  5,   6],
        [786, 786]]])

In [63]:
np.zeros((2,3))



array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.ones((3,3),dtype='int16')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [70]:
np.full((3,4),420)

array([[420, 420, 420, 420],
       [420, 420, 420, 420],
       [420, 420, 420, 420]])

In [77]:
np.random.rand(2,2)

array([[0.40317274, 0.50004822],
       [0.67848509, 0.94898016]])

In [85]:
np.random.randint(-5,6,size=(2,3))

array([[-1,  0, -3],
       [-5, -3,  3]])

In [86]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,4,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [98]:
a=np.array([1,2,3])
b=a.copy()
b
b[0]=420
b

array([420,   2,   3])

In [ ]:



11111
10001
10901
10001
11111

