In [4]:
#arranging numbers b/w a,b with interval c
#[a,b,c]
import numpy as np
np.arange(10,26,5)
np.arange(10,20,2)


array([10, 12, 14, 16, 18])

In [9]:
#comparision
#element wise comparission
#array wise comparision

a=[1,2,4]
b=[2,4,4]
c=[1,2,4]
np.equal(a,b)
np.array_equal(a,c)


True

In [14]:
#broadcasting
a=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b=np.array([0,1,2])
a+b


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [18]:
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
b=np.array([[4,5,6],[1,2,3],[6,7,8]])
np.dot(a,b)
#np.matmul(a,b)

array([[ 24,  30,  36],
       [ 57,  72,  87],
       [ 79, 100, 121]])

In [ ]:
#chess board white=>0 black=>1
